platform :ios, '11.0'
use_frameworks!

target 'AppsFlyerAdobeExtension_Example' do
  pod 'AppsFlyerAdobeExtension', :path => '../'
  pod 'ACPAnalytics', '2.1.2'
  pod 'ACPCore', '~> 2.3.2'
  
  
  target 'AppsFlyerAdobeExtension_Tests' do
    inherit! :search_paths

    
  end
end
